### ISSUE TITLE
How to use component with x-if?

### ISSUE THREAD

**Issue by bubnenkoff** [Lomacar/Ewok#2]
I would like to change displaying items like:
```
        <template x-data x-if="Alpine.store('auth').menuItemsState['home']">
            <home-component></home-component>
        </template>    

        <template x-data  x-if="Alpine.store('auth').menuItemsState['docs']">
            <docs-component></docs-component>
        </template>
```        

But work fine only x-show, other variants or display both components at same time or produce an error about error cloning node. What is correct way to do such thing? 

For example when I am trying to switch to component with follow code I am getting an error:
```
        <div x-data x-if="Alpine.store('auth').menuItemsState['home']">
            <regions-component></regions-component>
        </div>    

        <div x-data x-if="Alpine.store('auth').menuItemsState['docs']">
            <docs-component></docs-component>
        </div>
```
error:        

```
cdn.min.js:1 Alpine Expression Error: Cannot read properties of undefined (reading 'cloneNode')

Expression: "Alpine.store('auth').menuItemsState['docs']"

 <div x-data x-if=​"Alpine.store('auth')​.menuItemsState['docs']​">​…​</div>​
Y @ cdn.min.js:1
Vt @ cdn.min.js:1
(anonymous) @ cdn.min.js:5
r @ cdn.min.js:5
tn @ cdn.min.js:1
cdn.min.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at o (cdn.min.js:5:32081)
    at cdn.min.js:5:32301
    at ye (cdn.min.js:5:1229)
    at cdn.min.js:5:974
    at Vt (cdn.min.js:1:4640)
    at cdn.min.js:5:32293
    at Array.r (cdn.min.js:5:15575)
    at tn (cdn.min.js:1:207)
```

**Comment by Lomacar** [comment]
This is another problem you are having with Alpine. Please only ask about Ewok questions here. I'm not actually sure what you are doing wrong there but I got something working for you here:
```html
<script>
  document.addEventListener('alpine:init', () => {
    Alpine.store('auth', {
      menuItemsState: 'home'
    })
  })
</script>

<template x-data x-if="$store.auth.menuItemsState == 'home'">
   <test-test></test-test>
</template>

<template id="test-test">
  Test
</template>
```
