### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_x_refs')

### ISSUE THREAD

**Issue by bubnenkoff** [Lomacar/Ewok#6]
Hi! I tried copy-past your code example (only changed name of component) in my project to be sure that I am doing all right. But got an error:
 Component:
 ```
 <template id="regions-component">
  <script>
      const privateVar = "I'll never tell."

      export let killCount = 0

      export function shoot(){
          let success = Math.round(Math.random())
          this.killCount += success
          xref('result').innerText = success ? 'Hit!' : 'Miss'
          xref('count').innerText = this.killCount
      }
  </script>
  
  <button onclick="this.props.shoot()">Shoot</button>
  <p x-ref="result"></p>
  <p>Kill Count: <span x-ref="count"></span></p>
</template>
```

Error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_x_refs')
    at Function.Qr.inline (cdn.min.js:5:31873)
    at u (cdn.min.js:5:1964)
    at cdn.min.js:5:4391
    at Array.forEach (<anonymous>)
    at cdn.min.js:5:4380
    at D (cdn.min.js:5:3323)
    at cdn.min.js:5:3296
    at Array.forEach (<anonymous>)
    at D (cdn.min.js:5:3285)
    at cdn.min.js:5:4349
```

![изображение](https://user-images.githubusercontent.com/6514326/150927370-b178d971-1245-4e5d-aedd-d3ec0ab98fc4.png)

**Comment by Lomacar** [comment]
Hmm, I believe I still needed to do some work with x-ref, but it is working fine for me: https://codepen.io/lomacar/pen/RwLXbNq.

How are you loading Ewok and Alpine?
